export interface LabItem {
  slug: string;
  title: string;
  description: string;
  href: string;
  image: string;
  icon?: React.ComponentType<{ className?: string }>;
  status: 'Active' | 'Completed' | 'Beta' | 'Research' | 'Development' | 'Alpha';
  type: 'tool' | 'study' | 'dataset' | 'model';
  tags: string[];
  featured?: boolean;
}

import { Brain, Code, Cpu, Database, GitBranch, Lightbulb, Terminal } from "lucide-react";

export const experiments: LabItem[] = [
  {
    slug: "sri",
    title: "Sri AI Assistant",
    description: "Meet our AI co-founder and studio assistant",
    href: "/labs/experiments/sri",
    image: "https://picsum.photos/seed/sri/600/400",
    icon: Brain,
    status: "Active",
    type: "tool",
    tags: ["ai", "assistant", "tool"],
    featured: true,
  },
  // additional demo experiments
  {
    slug: "vision-kit",
    title: "Vision Kit",
    description: "Image understanding toolkit",
    href: "/labs/experiments/vision-kit",
    image: "https://picsum.photos/seed/vision/600/400",
    icon: Cpu,
    status: "Development",
    type: "tool",
    tags: ["vision", "tool"],
  },
  {
    slug: "nlp-dataset-1",
    title: "NLP Dataset 1",
    description: "Large corpus for language models",
    href: "/labs/experiments/nlp-dataset-1",
    image: "https://picsum.photos/seed/nlp1/600/400",
    icon: Database,
    status: "Active",
    type: "dataset",
    tags: ["nlp", "dataset"],
  },
  {
    slug: "chat-model-x",
    title: "Chat Model X",
    description: "Conversational model tuned for dialogues",
    href: "/labs/experiments/chat-model-x",
    image: "https://picsum.photos/seed/chatx/600/400",
    icon: Brain,
    status: "Beta",
    type: "model",
    tags: ["model", "chat"],
  },
  {
    slug: "speech-study",
    title: "Speech Recognition Study",
    description: "Evaluating ASR techniques",
    href: "/labs/experiments/speech-study",
    image: "https://picsum.photos/seed/speech/600/400",
    icon: Lightbulb,
    status: "Active",
    type: "study",
    tags: ["speech", "study"],
  },
  {
    slug: "code-model-z",
    title: "Code Model Z",
    description: "Generative coding model",
    href: "/labs/experiments/code-model-z",
    image: "https://picsum.photos/seed/codez/600/400",
    icon: Code,
    status: "Development",
    type: "model",
    tags: ["code", "model"],
  },
  {
    slug: "data-viz-tool",
    title: "Data Viz Tool",
    description: "Interactive data visualization",
    href: "/labs/experiments/data-viz",
    image: "https://picsum.photos/seed/viz/600/400",
    icon: GitBranch,
    status: "Beta",
    type: "tool",
    tags: ["visualization", "tool"],
  },
  {
    slug: "multimodal-dataset",
    title: "Multimodal Dataset",
    description: "Images paired with text captions",
    href: "/labs/experiments/multimodal-dataset",
    image: "https://picsum.photos/seed/multi/600/400",
    icon: Database,
    status: "Active",
    type: "dataset",
    tags: ["multimodal", "dataset"],
  },
  {
    slug: "rl-study",
    title: "Reinforcement Learning Study",
    description: "Experimenting with RL algorithms",
    href: "/labs/experiments/rl-study",
    image: "https://picsum.photos/seed/rl/600/400",
    icon: Lightbulb,
    status: "Development",
    type: "study",
    tags: ["rl", "study"],
  },
  {
    slug: "quantization-tool",
    title: "Quantization Tool",
    description: "Model optimization toolkit",
    href: "/labs/experiments/quantization-tool",
    image: "https://picsum.photos/seed/quant/600/400",
    icon: Terminal,
    status: "Active",
    type: "tool",
    tags: ["optimization", "tool"],
  },
  {
    slug: "translation-model",
    title: "Translation Model",
    description: "Multilingual translation model",
    href: "/labs/experiments/translation-model",
    image: "https://picsum.photos/seed/translate/600/400",
    icon: Brain,
    status: "Beta",
    type: "model",
    tags: ["translation", "model"],
  },
  {
    slug: "ethics-study",
    title: "AI Ethics Study",
    description: "Researching ethical implications of AI",
    href: "/labs/experiments/ethics-study",
    image: "https://picsum.photos/seed/ethics/600/400",
    icon: Lightbulb,
    status: "Active",
    type: "study",
    tags: ["ethics", "study"],
  },
  {
    slug: "compression-dataset",
    title: "Compression Dataset",
    description: "Dataset for model compression research",
    href: "/labs/experiments/compression-dataset",
    image: "https://picsum.photos/seed/compress/600/400",
    icon: Database,
    status: "Development",
    type: "dataset",
    tags: ["compression", "dataset"],
  },
  {
    slug: "doc-assistant",
    title: "Intelligent Document Assistant",
    description: "AI-powered document analysis & Q&A",
    href: "/labs/experiments/document-assistant",
    image: "https://picsum.photos/seed/doc/600/400",
    icon: Database,
    status: "Beta",
    type: "study",
    tags: ["nlp", "study"],
  },
  {
    slug: "culture-insights",
    title: "Cultural Insights Engine",
    description: "Analyzing cultural trends from social data",
    href: "/labs/experiments/cultural-insights",
    image: "https://picsum.photos/seed/culture/600/400",
    icon: Lightbulb,
    status: "Research",
    type: "dataset",
    tags: ["social", "dataset"],
  },
];

// Legacy tools kept for reference but will be merged into experiments array.
export const tools: LabItem[] = [
  {
    slug: "code-playground",
    title: "Code Playground",
    description: "Interactive coding environment for experiments",
    href: "/labs/tools/playground",
    image: "https://picsum.photos/seed/playground/600/400",
    icon: Code,
    status: "Alpha",
    type: "tool",
    tags: ["tool", "git"],
  },
  {
    slug: "model-hub",
    title: "AI Model Hub",
    description: "Collection of fine-tuned AI models",
    href: "/labs/tools/model-hub",
    image: "https://picsum.photos/seed/model/600/400",
    icon: Cpu,
    status: "Development",
    type: "tool",
    tags: ["tool", "cli"],
  },
  {
    slug: "version-control",
    title: "Version Control",
    description: "AI-powered version control system",
    href: "/labs/tools/version-control",
    image: "https://picsum.photos/seed/version/600/400",
    icon: GitBranch,
    status: "Alpha",
    type: "tool",
    tags: ["tool", "git"],
  },
  {
    slug: "cli-toolkit",
    title: "CLI Toolkit",
    description: "Command-line interface for AI workflows",
    href: "/labs/tools/cli",
    image: "https://picsum.photos/seed/cli/600/400",
    icon: Terminal,
    status: "Development",
    type: "tool",
    tags: ["tool", "cli"],
  },
];
